<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 3.1.6 on 2021-02-22 16:22
=======
# Generated by Django 3.0.6 on 2021-02-22 17:15
>>>>>>> a990452d70a8d9bed15bae2a09bee1b658c252a8
=======
# Generated by Django 3.0.6 on 2021-02-22 17:15
>>>>>>> a990452d70a8d9bed15bae2a09bee1b658c252a8

import Forum.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='post/default.jpg', upload_to=Forum.models.UserProfile.upload_location, verbose_name='Image')),
                ('bio', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('faculty', models.CharField(blank=True, default='', max_length=250)),
                ('department', models.CharField(blank=True, default='', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('images', models.ImageField(default='post/default.jpeg', upload_to=Forum.models.PostModel.upload_location, verbose_name='Image')),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(max_length=250, unique_for_date='Published')),
                ('Published', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='Published', max_length=250)),
                ('faculty', models.CharField(choices=[('BUS', 'BUS'), ('FAD', 'FAD'), ('FOE', 'FOE'), ('University', 'University'), ('FOST', 'FOST')], default='News', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
=======
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
=======
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
>>>>>>> a990452d70a8d9bed15bae2a09bee1b658c252a8
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('body', models.TextField()),
                ('published', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='published', max_length=50)),
                ('faculty', models.CharField(choices=[('FAD', 'FAD'), ('FOE', 'FOE'), ('BUS', 'BUS'), ('University', 'University'), ('FOST', 'FOST')], default='University', max_length=50)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> a990452d70a8d9bed15bae2a09bee1b658c252a8
            ],
            options={
                'ordering': ('-Published',),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('datePosted', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
<<<<<<< HEAD
<<<<<<< HEAD
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Forum.comments')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Forum.postmodel')),
=======
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Forum.Comments')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Forum.Post')),
>>>>>>> a990452d70a8d9bed15bae2a09bee1b658c252a8
=======
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Forum.Comments')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Forum.Post')),
>>>>>>> a990452d70a8d9bed15bae2a09bee1b658c252a8
            ],
        ),
    ]
