# Generated by Django 3.1.6 on 2021-02-22 13:26

import Forum.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='faculty',
            field=models.CharField(choices=[('BUS', 'BUS'), ('FOST', 'FOST'), ('FAD', 'FAD'), ('FOE', 'FOE'), ('University', 'University')], default='University', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='published', max_length=50),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='post/default.jpg', upload_to=Forum.models.UserProfile.upload_location, verbose_name='Image')),
                ('bio', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('faculty', models.CharField(blank=True, default='', max_length=250)),
                ('department', models.CharField(blank=True, default='', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
