# Generated by Django 3.0.6 on 2021-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='faculty',
            field=models.CharField(choices=[('FOST', 'FOST'), ('University', 'University'), ('FAD', 'FAD'), ('BUS', 'BUS'), ('FOE', 'FOE')], default='University', max_length=50),
        ),
    ]
