# Generated by Django 3.1.6 on 2021-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='faculty',
            field=models.CharField(choices=[('FOE', 'FOE'), ('University', 'University'), ('BUS', 'BUS'), ('FOST', 'FOST'), ('FAD', 'FAD')], default='News', max_length=50),
        ),
    ]
