# Generated by Django 3.1.6 on 2021-02-22 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_auto_20210222_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Forum.comments'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='faculty',
            field=models.CharField(choices=[('FOE', 'FOE'), ('University', 'University'), ('BUS', 'BUS'), ('FAD', 'FAD'), ('FOST', 'FOST')], default='News', max_length=50),
        ),
    ]
