# Generated by Django 3.1.6 on 2021-02-24 09:12

import Forums.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='post/default.jpg', upload_to=Forums.models.UserProfile.upload_location, verbose_name='Image')),
                ('bio', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('faculty', models.CharField(blank=True, default='', max_length=250)),
                ('department', models.CharField(blank=True, default='', max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('images', models.ImageField(default='post/default.jpeg', upload_to=Forums.models.PostModel.upload_location, verbose_name='Image')),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=250, unique_for_date='Published')),
                ('Published', models.DateTimeField(auto_now=True)),
                ('Faculty', models.CharField(choices=[('FOST', 'FOST'), ('FOE', 'FOE'), ('General', 'General'), ('FAD', 'FAD'), ('BUS', 'BUS')], default='Published', max_length=250)),
                ('Status', models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='University', max_length=50)),
                ('Update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forumPost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-Published',),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Forums.comments')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Forums.postmodel')),
            ],
        ),
    ]
