# Generated by Django 3.1.6 on 2021-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='Faculty',
            field=models.CharField(choices=[('FAD', 'FAD'), ('FOE', 'FOE'), ('BUS', 'BUS'), ('FOST', 'FOST'), ('General', 'General')], default='Published', max_length=250),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='Published',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='Status',
            field=models.CharField(choices=[('published', 'published'), ('draft', 'draft')], default='University', max_length=50),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='Update',
            field=models.DateField(auto_now=True),
        ),
    ]
