# Generated by Django 3.1.6 on 2021-02-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0002_auto_20210223_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='datePosted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='Faculty',
            field=models.CharField(choices=[('FOST', 'FOST'), ('FOE', 'FOE'), ('BUS', 'BUS'), ('General', 'General'), ('FAD', 'FAD')], default='Published', max_length=250),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='Published',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='Status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='University', max_length=50),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='Update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
