# Generated by Django 3.1.6 on 2021-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0003_auto_20210224_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='Faculty',
            field=models.CharField(choices=[('General', 'General'), ('FOE', 'FOE'), ('FAD', 'FAD'), ('FOST', 'FOST'), ('BUS', 'BUS')], default='General', max_length=250),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='Status',
            field=models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default='Published', max_length=50),
        ),
    ]
