# Generated by Django 3.1.6 on 2021-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0004_auto_20210224_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='Faculty',
            field=models.CharField(choices=[('BUS', 'BUS'), ('General', 'General'), ('FAD', 'FAD'), ('FOST', 'FOST'), ('FOE', 'FOE')], default='General', max_length=250),
        ),
    ]
