# Generated by Django 2.2.18 on 2021-02-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forums', '0006_auto_20210203_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='Faculty',
            field=models.CharField(choices=[('FOST', 'FOST'), ('FOE', 'FOE'), ('General', 'General'), ('FAD', 'FAD'), ('BUS', 'BUS')], default='General', max_length=250),
        ),
    ]
